language: java
cache:
  directories:
  - "$HOME/.m2/repository"
jdk:
- oraclejdk8
script:
- mvn package
deploy:
  provider: bintray
  file: ./bintray-upload-desc.json
  on: merged-prs
  user: breadfan
  key:
    secure: EkyZCn76XQ3Zm8gASZtXPKeORlcVlqSCIV1Bt20wyBALPb/Whi6PDcZLoTa1zfRhmU7A4qViuwqEz6NgvJjmvDiu8EefL6zEMGvI35PQ1RmnaTeOvCwkfy5q4njwQZf+ELSlR32skO1eQEr/rbg3+oGM/fJpWpFrvSFy5+qRKyW6jiWEYx/RihMArfyFpLtMnh7m9Db0OlfAJ1RiXdjc2ZyrN+1LDr692NoyVjmeod4g1EHcnIyN7Cgh0t1B2H3rl5UbEydFB3lwaeu3IPDLyuhM1febY9c+DLKubHNMypPElmFA5IOijyRmRh5k8jlXhaaD6Ml7DIhA9PHBT5uWS892wl10JJX6Pv0IEKXvzbdoGJVfCSjWl+UaMPTv5d4KA3MJpkvq74y5eeChuPz4mSmvD5b10wlmmYrSZM6vIQG7RBrGODsUrO4ImYPgLdw+t8OyCyfxVw+RzZAPpeQKgLL6kX1d4lyBoy20CFrwlg5UvBITQg0cMZffD9yJT6GsmskFyrfhoEnaiywLuQNJHISan46RdTma0q+pT3/IHJ0wO/Hm9zE9yV82VaeOj0RtfWsngyWW/n9QJSNiG2uGIZ9A4ACY31qNXOkY/nyoKqbwcgoZIaL89+CEe9gpAb4QNaehKWbu0Sx8IExbHPHGm/MBqeppLj+v7P7eJ0iAkJI=
